spring:
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        password: 'devP@ssword1'
        username: developer
    jpa:
        database-platform: org.hibernate.dialect.MySQLDialect
        generate-ddl: false
        hibernate:
          ddl-auto: none
        show-sql: true